import Head from "next/head";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useTranslation } from "next-i18next";
import { useRouter } from "next/router";
import Link from "next/link";

export default function Home() {
  const router = useRouter();
  const { t, i18n } = useTranslation();
  return (
    <>
      <Head>
        <title>Oficzech - Business Consultant</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-3xl font-bold underline">Hello world!</h1>
      <br />
      <h1>{i18n.language}</h1>
      <h1>{router.locales?.length}</h1>

      <Link href="/" locale={i18n.language}>
        Home
      </Link>
      <br />
      <Link href="/about" locale={i18n.language}>
        About
      </Link>
      <br />
      <br />
      <br />
      {router.locales?.map((locale) => (
        <Link href={router.asPath} locale={locale} key={locale}>
          <span>{locale}</span>
        </Link>
      ))}
      {t("common:yes")}
    </>
  );
}

export async function getStaticProps({ locale }: any) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ["common", "home"])),
      // Will be passed to the page component as props
    },
  };
}
